<div style="float: left; width: 25%;">
<ul>
<img src="http://www.minesnewsroom.com/sites/default/files/wysiwyg-editor/photos/CO-Mines-logo-stacked-4C-200x235w.png" style="height: 115px;">
</ul>
</div>

<div style="float: right; width: 75%;">
<ul>
    <h1> CSCI 250 - Building a Sensor System </h1>
    <span style="color:red">
        <h2> 1D numpy arrays </h2>
    </span>
</ul>
</div>

# Objectives
* Introduce 1D numpy arrays and operations
* Discuss numpy array 
    * attributes
    * slicing and striding

# Resources
* [Numpy.org](http://www.numpy.org)

# import
Numpy comes with lots of functions specifically designed for array operations. Numpy **methods** can be accessed by typing the module name, followed by a dot, followed by the **TAB** key. The name of the method followed by **?** returns the associated selfdoc. Also, each numpy objects has specific associated methods which can be accessed using the same procedure.

In [3]:
import numpy as np

n = 6

# array creation
There are multiple mechanisms to define 1D numpy arrays.

## list conversion
Use the function **array** to create a numpy array from a Python list.

`np.array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)`

In [2]:
x = np.array( [2,3,4,5], dtype='float')
print(x)
type(x)

[2. 3. 4. 5.]


numpy.ndarray

## sequence conversion
Use the function **array** to create a numpy array from a sequence defined with function range.

`np.array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)`

In [3]:
x = np.array( range(n), dtype='float')
print(x)
type(x)

[0. 1. 2. 3. 4. 5.]


numpy.ndarray

## zeros()
Returns a new array of given shape and type, filled with zeros.

`np.zeros(shape, dtype=None, order='C')`

In [4]:
zI = np.zeros(n, dtype=int)
zF = np.zeros(n, dtype=float)
zB = np.zeros(n, dtype=bool)
zC = np.zeros(n, dtype=complex)

In [5]:
print(zI)
print(zF)
print(zB)
print(zC)

[0 0 0 0 0 0]
[0. 0. 0. 0. 0. 0.]
[False False False False False False]
[0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]


## ones()
Returns a new array of given shape and type, filled with ones.

`np.ones(shape, dtype=None, order='C')`

In [6]:
oI = np.ones(n, dtype=int)
oF = np.ones(n, dtype=float)
oB = np.ones(n, dtype=bool)
oC = np.ones(n, dtype=complex)

In [7]:
print(oI)
print(oF)
print(oB)
print(oC)

[1 1 1 1 1 1]
[1. 1. 1. 1. 1. 1.]
[ True  True  True  True  True  True]
[1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j]


## arange()

Return evenly spaced values within a given interval. It can be used to contstruct numpy arrays for different data types, as specified by **dtype**. (Type bool has no meaning in this context.)

`np.arange([start,] stop[, step,], dtype=None)`

In [8]:
a = np.arange(2.0, 5.0, 0.5)
print(a)

[2.  2.5 3.  3.5 4.  4.5]


## linspace()
Returns evenly spaced numbers over a specified interval. It can be used to contstruct numpy arrays for different data types, as specified by **dtype**. (Type bool has no meaning in this context.)

`np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)`

The function **linspace** specifies how many values we want in an interval, unlike the function **arange** which specifies the increment between the values. Therefore, linspace enables arrays to have known start and stop values.

In [9]:
a = np.linspace(2.0, 5.0, 7)
print(a)

[2.  2.5 3.  3.5 4.  4.5 5. ]


## logspace()
Return numbers spaced evenly on a log scale. It can be used to contstruct numpy arrays for different data types, as specified by **dtype**. (Type bool has no meaning in this context.)

`np.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None)`

In [10]:
a = np.logspace(-2, 2, 5)
print(a)

[1.e-02 1.e-01 1.e+00 1.e+01 1.e+02]


# array indexing

We can access an element of an array using the index of the elemnent (start w/ 0).

In [11]:
a = np.ones(n, dtype='float')
print(a)

[1. 1. 1. 1. 1. 1.]


In [12]:
a[ 3 ] = 0
print(a)

[1. 1. 1. 0. 1. 1.]


In [13]:
# can also use negative indexes
a[ -4 ] = 0
print(a)

[1. 1. 0. 0. 1. 1.]


# array slicing
We can access/modify a range of elements using min and max array indexes. 

In [14]:
a = np.ones(n, dtype='float')
print(a)

[1. 1. 1. 1. 1. 1.]


In [15]:
a[ 3:7 ] = 0
print(a)

[1. 1. 1. 0. 0. 0.]


# array attributes
Array attributes reflect information that is intrinsic to the array itself and allow to get and set intrinsic properties of the array without creating a new array. 

<img src="http://www.dropbox.com/s/fcucolyuzdjl80k/todo.jpg?raw=1" width="10%" align="left">
Explain the meaning and explore the use of specific **array attributes**.
Add comments capturing the purpose and usage for the listed attributes, and include other examples demonstrating different features.

In [16]:
o = np.ones( n )
# Generate a numpy array of all ones of size n

In [17]:
o.ndim
# Return the dimension of numpy array o

1

In [19]:
o.shape
# Return the shape (number of elements in the numpy array, dimension)

(6,)

In [21]:
o.size
# Return the shape of a numpy array (number of elements of the array)

6

In [23]:
o.dtype
# Return the data type of the elements in the numpy array

dtype('float64')

In [25]:
o.nbytes
# Return the number of bytes used to store the data in the numpy array

48

# array methods
Array methods are facilitate efficient operations on numpy arrays.

<img src="http://www.dropbox.com/s/fcucolyuzdjl80k/todo.jpg?raw=1" width="10%" align="left">
Explain the meaning and explore the use of specific **array methods**.
Add comments capturing the purpose and usage for the listed methods, and include other examples demonstrating different features.

In [27]:
a = np.arange(1,n,0.5)
# Generate a numpy array of n elements starting at 1 and incrementing by .5 each element

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5]


## ndarray.fill()
Fill an array with a scalar value.

`ndarray.fill(value)`

In [29]:
a = np.empty( n )
a.fill(-1.)
print(a)
# Generate an empty array of size n, then fill the array with a float of 1 in each element

[-1. -1. -1. -1. -1. -1.]


## ndarray.item()
Copy an element of an array to a standard Python scalar and return it.

`ndarray.item(*args)`

In [31]:
a = np.arange(1,n,0.5)
print(a)
print(a.item(5))
# Generate a numpy array of n size and pull the 6th element or the array and return it

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5]
3.5


## ndarray.nonzero()
Return the indices of the elements that are non-zero.

`ndarray.nonzero()`

In [33]:
a = np.arange(1,n) %2
print(a)
print(a.nonzero())
# After array generation return any element that is not a zero

[1 0 1 0 1]
(array([0, 2, 4], dtype=int64),)


## ndarray.put()
Replaces specified elements of an array with given values.

`ndarray.put(ind, v, mode='raise'`)

In [35]:
a = np.array( [4, 3, 5, 7, 6, 8] )
indices = [0,1,4]
values = [-1,-2,-3]
a.put(indices,values)
print(a)
# Replace elements in numpy array with passed value

[-1 -2  5  7 -3  8]


## ndarray.clip()
Clip (limit) the values in an array.

`ndarray.clip(a_min, a_max, out=None)`

In [36]:
a = np.arange(1,n,0.5) - 3
print(a)

[-2.  -1.5 -1.  -0.5  0.   0.5  1.   1.5  2.   2.5]


In [38]:
print(a.clip(-1,1))
# limit the values of all elements in an array to between -1 and 1

[-1.  -1.  -1.  -0.5  0.   0.5  1.   1.   1.   1. ]


## ndarray.round()
Evenly round to the given number of decimals.

`ndarray.around(decimals=0, out=None)`

In [40]:
a = np.arange(1,n,0.5)
a.round(0)
# Round all elements in the array to zero decimal places

array([1., 2., 2., 2., 3., 4., 4., 4., 5., 6.])

## ndarray.sort()
Return a sorted copy of an array.

`ndarray.sort(axis=-1, kind='quicksort', order=None)`


In [42]:
a = np.arange(n,1,-1)
print(a)
a.sort()
print(a)
# Reorders the array elements to index from lower to higher values

[6 5 4 3 2]
[2 3 4 5 6]


## ndarray.take()
Take elements from an array along an axis.

`ndarray.take(indices, axis=None, out=None, mode='raise')`

In [44]:
a = np.array( [4, 3, 5, 7, 6, 8], dtype=float)
indices = [0,1,4]
a.take(indices)
# Grab the values from an array at index values 0,1,4

array([4., 3., 6.])

## ndarray.min()
Return the minimum of an array or minimum along an axis.

`ndarray.min(axis=None, out=None, keepdims=<class 'numpy._globals._NoValue'>)`

## ndarray.max()
Return the maximum of an array or maximum along an axis.

`ndarray.max(axis=None, out=None, keepdims=<class 'numpy._globals._NoValue'>)`


## ndarray.mean()
Compute the arithmetic mean along the specified axis.

`ndarray.mean(axis=None, dtype=None, out=None, keepdims=<class 'numpy._globals._NoValue'>)`


## ndarray.std()
Compute the standard deviation along the specified axis.

`ndarray.std(axis=None, dtype=None, out=None, ddof=0, keepdims=<class 'numpy._globals._NoValue'>)`


## ndarray.var()
Compute the variance along the specified axis.

`ndarray.var(axis=None, dtype=None, out=None, ddof=0, keepdims=<class 'numpy._globals._NoValue'>)
`

In [46]:
a = np.array( [4, 3, 5, 7, 6, 8], dtype=float)
print(a.min())
print(a.min())
print(a.mean())
print(a.var())
print(a.std())
# Return summary statistics of numpy arrays

3.0
3.0
5.5
2.9166666666666665
1.707825127659933


## ndarray.argmin()
Returns the indices of the minimum values along an axis.

`ndarray.argmin(axis=None, out=None)`

## ndarray.argmax()
Returns the indices of the maximum values along an axis.

`ndarray.argmax(axis=None, out=None)`


## ndarray.argsort()
Returns the indices that would sort an array.

`ndarray.argsort(axis=-1, kind='quicksort', order=None)`

In [48]:
a = np.array( [4, 3, 5, 7, 6, 8], dtype=float )
print(a)

print(a.argmin())
print(a.argmax())
print(a.argsort())
# Returns summary statistics of the numpy array in terms of indices

[4. 3. 5. 7. 6. 8.]
1
5
[1 0 2 4 3 5]


## ndarray.sum()
Return the sum of array elements over a given axis.

`ndarray.sum(axis=None, dtype=None, out=None, keepdims=<class 'numpy._globals._NoValue'>)`

## ndarray.prod()
Return the product of array elements over a given axis.

`ndarray.prod(axis=None, dtype=None, out=None, keepdims=<class 'numpy._globals._NoValue'>)`

In [50]:
a = np.arange(1,n)
print(a)

print(a.sum())
print(a.prod())
# Returns sum and product of all elements in an array

[1 2 3 4 5]
15
120


## ndarray.cumsum()
Return the cumulative sum of the elements along a given axis.

`ndarray.cumsum(axis=None, dtype=None, out=None)`

## ndarray.cumprod()
Return the cumulative product of the elements along a given axis.

`ndarray.cumprod(axis=None, dtype=None, out=None)`

In [52]:
a = np.arange(1,n)
print(a)

print(a.cumsum())
print(a.cumprod())
# Calculate cumultive values of sum and products of the array

[1 2 3 4 5]
[ 1  3  6 10 15]
[  1   2   6  24 120]


## ndarray.real
Return the real part of the complex argument.

`ndarray.real`


## ndarray.imag
Return the imaginary part of the complex argument.

`ndarray.real`

In [53]:
a = np.array( [4, 3, 5, 7, 6, 8], dtype=complex)
print(a)

print(a.real)
print(a.imag)
# For each element in a numpy array return the real and imaginary values of it

[4.+0.j 3.+0.j 5.+0.j 7.+0.j 6.+0.j 8.+0.j]
[4. 3. 5. 7. 6. 8.]
[0. 0. 0. 0. 0. 0.]


<img src="https://www.dropbox.com/s/wj23ce93pa9j8pe/demo.png?raw=1" width="10%" align="left">
# Exercise

A sequence for computing number $\pi$ credited to the mathematician **Gottfried Leibniz** is:

$\dfrac{\pi}{4} = \sum\limits_{i=1}^{n} \dfrac{ (-1)^{i+1} }{2i-1}$

* Use numpy to compute number $\pi$ for a set number of terms.
* Compare this approximation with the $\pi$ value provided by the `math` module.

In [1]:
n = 1000

Define a numpy array for integers $i<n$:

In [4]:
i = np.arange(1,n)

Compute the terms of the series using array operations:

In [5]:
myTerms = 4.0*( pow(-1,i+1) / (2*i-1) )

Compute $\pi$ using numpy functions:

In [6]:
myPi = myTerms.sum()

Compare the user-defined $\pi$ with the one provided by `math`:

In [18]:
import math

print('     my pi:',myPi)
print('   math pi:',math.pi)
print('difference:',myPi-math.pi)

     my pi: 3.3396825396825403
   math pi: 3.141592653589793
difference: 0.19808988609274714


<img src="https://www.dropbox.com/s/wj23ce93pa9j8pe/demo.png?raw=1" width="10%" align="left">
# Exercise

Use a NumPy array to approximate $\pi$ using the equation

$\pi \approx \sqrt{12} \sum\limits_{i=0}^{n} \dfrac{(-3)^{-i}}{2i+1}$.

* Use numpy to compute number $\pi$ for a set number of terms.
* Compare this approximation with the $\pi$ value provided by the `math` module.

In [1]:
import math
n = 1000
i = np.arange(0,n)
newTerms = (pow(-3.0, -i)/((2.0*i) + 1))
almostPi = newTerms.sum()
newPi = math.sqrt(12.0) * almostPi
print(newPi)
# Compare my PI to math.pi
print('     my pi:',newPi)
print('   math pi:',math.pi)
print('difference:',newPi-math.pi)

NameError: name 'np' is not defined